version: '3'

services:
  database:
    image: mariadb:10.1.48
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: [3306]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestBook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
      
  redis:
    image: redis:5-alpine
    ports: [6379]
        
    #blackfire:
     # image: blackfire/blackfire
      #env_file: .env.local
      #ports: [8707]  